spring:
  application:
    name: sistema-gestao-institucional
    version: @project.version@
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      file: compose-dev.yaml
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/sistema_gestao_institucional
    username: ${DB_USERNAME:user_sistema_gestao_institucional}
    password: ${DB_PASSWORD:12345678}
  jpa:
    show-sql: false
    open-in-view: false
  threads:
    virtual:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
minio:
  url: http://${MINIO_HOST:minio}:9000
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET_NAME:sistema-gestao-institucional}
jwt:
  secret: ${JWT_SECRET:6f27a8212e780877821336520f8ba1baa189f4ab8cd3f30a0e2c84f0e6bfecb7}
  expiration: 300000 # 5 minutos em milissegundos
  refresh-expiration: 3600000 # 1 hora em milissegundos
