spring:
  application:
    name: sistema-gestao-institucional
    version: @project.version@
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:true}
      file: compose-dev.yaml
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://localhost:5482/sistema_gestao_institucional
    username: ${DB_USERNAME:user_sistema_gestao_institucional}
    password: ${DB_PASSWORD:12345678}
  jpa:
    show-sql: false
    open-in-view: false
  threads:
    virtual:
      enabled: true
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET_NAME:sistema-gestao-institucional}
